title: Your awesome title
author: GitHub User
email: your-email@domain.com
copyright: © 2022 GitHub User
description:  Write an awesome description for your new site here. 
              You can edit thisline in _config.yml. It will appear 
              in your document head meta (forGoogle search results) and in your feed.xml site description.
show_excerpts: false # set to true to show excerpts on the homepage

lin:
  date_format: "%b %-d, %Y"

  # you can put a path to the author avatar image
  avatar_path: 

  # generate social links
  social_links:
    twitter: jekyllrb
    github:  jekyll
    medium:  jekyll
    rss: rss
    dribbble: jekyll
    facebook: jekyll
    flickr:   jekyll
    instagram: jekyll
    linkedin: jekyll
    pinterest: jekyll
    youtube_user: jekyll
    youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    telegram: jekyll
    googleplus: +jekyll
    keybase: jekyll

theme: jekyll-lin

plugins:
 - jekyll-feed